/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "types.h"

bool_t
xdr_Request (XDR *xdrs, Request *objp)
{
	//register int32_t *buf;

	if (!xdr_array (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->last))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Response (XDR *xdrs, Response *objp)
{
	//register int32_t *buf;

	 if (!xdr_bool (xdrs, &objp->error))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}
